### ISSUE TITLE
Fix Sphinx version constraint

### ISSUE THREAD

**Issue by jmbowman** [openedx/edx-sphinx-theme#197]
Sphinx 6 was recently released, and isn't compatible with this theme.  This repo is pinned to an ancient version of Sphinx, but that pin isn't propagated as a package dependency because the fix that would do that was never released.  A PR to unpin Sphinx was started, but never merged.  We want to stop using this theme, but the upgrade guide to switch to the new preferred theme isn't ready yet.  So for now, let's just fix things enough to stop breaking the upgrade jobs in other repos:

1. Add a constraint for Sphinx<6.0.0 to the common_constraints.txt file in edx-lint, so nothing upgrades to the new Sphinx version for now.
2. Finish the work started in https://github.com/openedx/edx-sphinx-theme/pull/157 , but constrain to Sphinx<6.0.0 instead of fully removing the constraint.
3. Release a new version that has the correct Sphinx constraint in the package metadata.
4. Create a followup issue to remove the common_constraints.txt entry, but don't start it for a few weeks.  That should give other repos time to either get the appropriate Sphinx constraint via edx-sphinx-theme or migrate off of edx-sphinx theme.

**Comment by UsamaSadiq** [comment]
Created PR https://github.com/openedx/edx-lint/pull/306 for the 1st step of the issue.

**Comment by jmbowman** [comment]
Before removing the common constraint, we may want to review https://blog.readthedocs.com/sphinx6-upgrade/ and make sure we've made any changes needed for Read the Docs builds to work with Sphinx 6.

**Comment by awais786** [comment]
Every thing is done except 4th part. Will remove this after 2 weeks.
